- name: Create Argocd namespace
  command: kubectl create namespace argocd
  register: ns_result
  failed_when:
    - ns_result.rc != 0
    - '"already exists" not in ns_result.stderr'
  changed_when: ns_result.rc == 0

- name: ArgoCD Install
  command: >
    kubectl apply -n argocd
    --server-side
    -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

- name: Await for ArgoCD
  command: >
    kubectl wait --for=condition=available deployment/argocd-server
    -n argocd --timeout=180s

- name: Apply ArgoCD Application manifest
  command: >
    kubectl apply -f {{ playbook_dir }}/../../argocd/application.yaml