apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kata-challenge
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: >
      backend=ghcr.io/ch1gu1/epam-katas-challenge-backend:latest,
      frontend=ghcr.io/ch1gu1/epam-katas-challenge-frontend:latest
    argocd-image-updater.argoproj.io/backend.update-strategy: digest
    argocd-image-updater.argoproj.io/frontend.update-strategy: digest
    argocd-image-updater.argoproj.io/backend.pull-secret: pullsecret:argocd/ghcr-image-updater
    argocd-image-updater.argoproj.io/frontend.pull-secret: pullsecret:argocd/ghcr-image-updater
spec:
  project: default
  source:
    repoURL: https://github.com/CH1GU1/epam-katas-challenge
    targetRevision: main
    path: helm/kata-challenge
  destination:
    server: https://kubernetes.default.svc
    namespace: kata-challenge
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
